from .mean_squared_error import MeanSquaredError
from .categorical_cross_entropy import CategoricalCrossEntropy
from .kl_divergence import KLDivergence
from .cosine_similarity import CosineSimilarityLoss
